version: "2"

# More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "80:80/tcp"
      - "443:443/tcp"
    environment:
      TZ: 'America/Santiago'
      WEBPASSWORD: 'Hola1234.-'
    # Volumes store your data between container upgrades
    # Originales:
    # './etc-pihole/:/etc/pihole/'
    # './etc-dnsmasq.d/:/etc/dnsmasq.d/'
    volumes:
      - 'etc-pihole:/etc/pihole/'
      - 'etc-dnsmasq.d:/etc/dnsmasq.d/'
    # Recommended but not required (DHCP needs NET_ADMIN)
    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    cap_add:
      - NET_ADMIN
    restart: allways
volumes:
  etc-pihole: {}
  etc-dnsmasq.d: {}
